### ISSUE TITLE
gulp fails "EPERM: operation not permitted, scandir "

### ISSUE THREAD

**Issue by noreddineelga** [LucasBassetti/pentaho-cdf-angular-boilerplate#2]
I am working on windows 10 and I am runing git bash as administrator .

This error occures every time I execute `gulp` or `gulp test`
Here is error message in powershell:
for `gulp` :  
```
events.js:160

      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, scandir 'D:\Atom workspace\pentaho-cdf-angular-boilerplate\.tmp\serve\app'
    at Error (native)
```

for `gulp test`
```
Using gulpfile D:\Atom workspace\pentaho-cdf-angular-boilerplate\gulpfile.js
[10:39:59] Starting 'scripts'...
[10:40:00] Starting 'styles'...
[10:40:00] gulp-inject 2 files into index.scss.
[10:40:00] 'styles' errored after 564 ms
[10:40:00] Error: EPERM: operation not permitted, mkdir 'D:\Atom workspace\pentaho-cdf-angular-boilerplate\.tmp\serve\app'
    at Error (native)
```

**Comment by LucasBassetti** [comment]
No idea what's going on. 

Try to look these links and see if you can solve this problem:
1. [http://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows](http://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows)
2. [https://github.com/npm/npm/issues/10826](https://github.com/npm/npm/issues/10826)
3. [https://github.com/gulpjs/gulp/issues/660](https://github.com/gulpjs/gulp/issues/660)

**Comment by noreddineelga** [comment]
I solved the problem, Thank you !

I have one more question, I did all construction in Readme, but i didn't find any command for runing the project (like grunt mockserver:open with grunt) , what's the equivalent command using gulp

**Comment by LucasBassetti** [comment]
What do you do to solve this problem?

You can use the command `gulp serve` to running the project and watch the file changes. Every change the files will be zipped and imported to pentaho again.

**Comment by noreddineelga** [comment]
Honestly I didn't do anything magic, I let the server runing(`gulp server`) in power shell and i ran  an other power shell, where i exectued the command `gulp` so it worked fine.

I want to see the dashboard and make it as i want.
My goal is to use pentaho cdf in my angular project.

**Comment by saeed-asghari** [comment]
The source and destination folder should not just be readonly.

**Comment by PRBHARTI1** [comment]
I resolved this bug after removing extra comma found at every last item within function.
error: () => {
          Console.log('error found...');
        },  // unwanted comma is causing problem
      });

**Comment by elpinto007** [comment]
> The source and destination folder should not just be readonly.

I was getting a similar error message - this was the cause of it. My folders were read only for some reason.
